### ISSUE TITLE
ขอคำแนะนำเพื่อนำไปปรับปรุงแบบตัวอักษรละติน - ไทย

### ISSUE THREAD

**Issue by suppakit-** [cadsondemak/Sarabun#4]
สำหรับรุ่นนี้ มีการปรับตัวอักษรละตินให้แคบลงกว่ารุ่นดั้งเดิม เพื่อให้สัดส่วนรูปทรงของตัวอักษรสัมพันธ์กับตัวอักษรไทยมากขึ้น เนื่องจากตัวอักษรไทยเป็นลักษณะที่ค่อนข้างแคบ ตามแบบฉบับสัดส่วนอักษรไทย ในขณะเดียวกันก็ปรับตัวอักษรไทยบางตัวให้กว้างขึ้นด้วย และมีการลดระดับหัวตัวอักษรที่อยู่ตรงกลางให้ต่ำลงเล็กน้อย โดยพยายามรักษาสัดส่วนที่ดีของอักษรไทยไว้ และทำให้ดูร่วมสมัยมากขึ้น อย่างไรก็ดีผมต้องการคำแนะนำจากทุกท่านครับ ขอบคุณครับ :)
![sarabun](https://user-images.githubusercontent.com/10925808/37558873-b9d4130c-2a4d-11e8-83af-19d49cdd697b.png)

**Comment by AnuthinWongsunkakon** [comment]
The negative alley in ฑ could be improved. I think this problem is always there and it is the hard one to fix. Thai Loop  in bolder than bold weight is relatively new so we do not have many approach on how to fix this. I still would like to see the traditional approach in ท and ฑ. I would like to see you keep this design but the question is how to make ฑ work out like what you have in ท. Could you possibly reduce the size of the while head loop and the crease at the head loop altogether? This should make more room for the headlamp in the bolder weight. At the same time making the delta at the point where the front stem meets the diagonal stroke. This area is currently too dark anyway. Try it and see how did it go. I hope this would help you some.

**Comment by suppakit-** [comment]
ค้นหาแนวทาง และพยายามปรับแบบ ที่เป็นไปได้มากที่สุดครับ สำหรับ ฑ ซึ่งเป็นปัญหาในเชิงโครงสร้างของตัวอักษรเอง จะจัดการพื้นที่บริเวณหัวของ ฑ ในอัปเดตถัดไปครับ :D
